# Generated by Django 4.1 on 2024-06-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TaskApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="deadline",
        ),
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[("仕事", "仕事"), ("遊び", "遊び"), ("その他", "その他")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("低", "低"), ("中", "中"), ("高", "高")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Priority",
        ),
    ]
