# Generated by Django 4.1 on 2024-06-14 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TaskApp", "0002_remove_task_deadline_alter_task_category_and_more"),
        ("TaskApp", "0003_task_due_date"),
    ]

    operations = []
