# Generated by Django 4.1 on 2024-06-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TaskApp", "0005_task_completed_alter_task_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[("仕事", "仕事"), ("遊び", "遊び"), ("その他", "その他")],
                default="仕事",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("低", "低"), ("中", "中"), ("高", "高")], default="低", max_length=10
            ),
        ),
    ]
