# Generated by Django 4.1 on 2024-06-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TaskApp", "0007_task_created_at_alter_task_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
