# Generated by Django 4.1 on 2024-06-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserApp", "0004_userprofile_birthday_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(default="", max_length=30),
        ),
    ]
